version: "3"
services:
  gala-node:
    build: .
    container_name: "gala-node"
    restart: unless-stopped
    stdin_open: true
    tty: true
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "4001:4001"
    env_file:
      - .env
